### ISSUE TITLE
WtWSMS version

### ISSUE THREAD

**Issue by IhateTrains** [ijedi1234/Attila2CK2#1]
Hi, as I said on reddit I'd like to help with providing WtWSMS compatibility. Could you make a Collaborator? I would create a branch and work there :)

**Comment by ijedi1234** [comment]
Sent an invite. IRL events slowed me down a bit.

**Comment by ijedi1234** [comment]
I'm preparing documentation for a release, so you should be able to use a compiled exe soon.
